apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
    {{- include "sc-deployer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appname }}
    {{- include "sc-deployer.selectorLabels" . | nindent 4 }}
