replicaCount: 1
appname: sc-deployer
namespace: sequence-clock

image:
  repository: "192.168.1.243:5001/sequence-clock-deployer"
  pullPolicy: Always
  tag: "1.0"

imagePullSecrets: []
nameOverride: "sc-deployer"
fullnameOverride: "sc-deployer"

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
