name: SC-Watcher-Supreme Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_REPO_KEY }}
    - name: Build the Docker image
      run: cd watcher && docker build --ssh default . --file Dockerfile --tag john98nf/sc-watcher-supreme:$(date +%s)
